SELECT * FROM "USER";

--시퀀스 초기화
--(1)
--DROP, CREATE
DROP SEQUENCE USER_SEQ;

CREATE SEQUENCE USER_SEQ
INCREMENT BY 1
START WITH 2
MINVALUE 1
MAXVALUE 1000;

--(2)
--ALTER SEQUENCE 시퀀스명 INCREMENT BY -마지막 값;
--SELECT 시퀀스명.NEXTVAL FROM DUAL;
--ALTER SEQUENCE 시퀀스명 INCREMENT BY 1;
INSERT INTO "USER"
(USER_NUMBER, ID, PW, NAME, AGE, PHONE_NUMBER)
VALUES(1, 'hds1234', '1234', '한동석', 20, '01012341234');

TRUNCATE TABLE "USER";

SELECT * FROM "USER";