CREATE TABLE CAR(
	ID VARCHAR2(4),
	BRAND VARCHAR2(20),
	COLOR VARCHAR2(20),
	PRICE NUMBER(10),
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

ALTER TABLE CAR DROP CONSTRAINT CAR_PK;
ALTER TABLE CAR ADD CONSTRAINT CAR_PK PRIMARY KEY(ID);

INSERT INTO CAR
(ID, BRAND, COLOR, PRICE)
VALUES('A001', 'Benz', 'Black', 850000000);

SELECT * FROM CAR;

DROP TABLE CAR;

--한줄 주석
/*
 * 범위 주석
 */

/*
 * 애완동물 테이블 만들기
 * 종류, 나이, 먹이
 * 정보 한 개 추가해보기
 * 
 */
CREATE TABLE PET(
	"TYPE" VARCHAR2(10),
	AGE NUMBER(2),
	FEED VARCHAR2(10)
);

INSERT INTO PET
("TYPE", AGE, FEED)
VALUES('강아지', 5, '사료');

INSERT INTO PET
("TYPE", AGE, FEED)
VALUES('고양이', 2, '사료');

SELECT * FROM PET;

TRUNCATE TABLE PET;
----------------------------------------
INSERT INTO CAR
(ID, BRAND, COLOR, PRICE)
VALUES('A002', 'Audi', 'White', 650000000);

SELECT * FROM CAR;

ALTER TABLE CAR RENAME TO CAR2;

SELECT * FROM CAR2;

ALTER TABLE CAR2 ADD(RELEASED DATE);

INSERT INTO CAR2
(ID, BRAND, COLOR, PRICE, RELEASED)
VALUES('A003', 'BMW', 'Blue', 150000000, SYSDATE);

SELECT * FROM CAR2;

INSERT INTO CAR2
(ID, BRAND, COLOR, PRICE, RELEASED)
VALUES('A004', 'Bentley', 'Gray', 350000000, TO_DATE('2016-03-02 10:04:20', 'YYYY-MM-DD HH:MI:SS'));

SELECT * FROM CAR2;

ALTER TABLE CAR2 RENAME COLUMN BRAND TO NAME;

--COLOR를 C로 변경
ALTER TABLE CAR2 RENAME COLUMN COLOR TO C;

ALTER TABLE CAR2 DROP COLUMN C;

ALTER TABLE CAR2 RENAME TO CAR;

SELECT * FROM CAR;

TRUNCATE TABLE CAR;

DROP TABLE CAR;

/*
 * FLOWER 테이블 생성하기
 * 컬럼명 : ID, NAME, AGE, COLOR
 * ID는 PK로 설정한다.
 * FLOWER에서 FLOWER2로 테이블명 변경
 * FLOWER2에서 PRICE컬럼 추가
 * INSERT로 값 넣기(2개의 정보 넣기)
 * FLOWER2테이블 값 삭제(TRUNCATE)
 * FLOWER2테이블 전체 삭제(DROP)
 */








